# Generated by Django 3.2.1 on 2021-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('leave_application', models.TextField()),
                ('open_date', models.DateField(verbose_name="today's date")),
                ('present', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employeeOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('attendance_point', models.IntegerField()),
                ('project_point', models.IntegerField()),
                ('attitude_point', models.IntegerField()),
                ('work_quality_point', models.IntegerField()),
                ('leadership_point', models.IntegerField()),
                ('cooperation_point', models.IntegerField()),
                ('total_point', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
